repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: python3 -m unittest discover -s tests -p "*.py"
        language: python
        'types': [ python ]
        pass_filenames: false
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        exclude: "[a-zA-Z]*/(migrations)/(.)*"
        args: ["--check", "."]
